### ISSUE TITLE
Comments on generating services

### ISSUE THREAD

**Issue by djungelorm** [eXigentCoder/krpc-node#1]
I see you're generating the services using a call to `GetServices` and wanted to fill you in on how I do a similar thing for the existing kRPC clients.

The python and lua clients dynamically construct the services when they connect to the server, using a call to `GetServices`. The benefit of this is that the client code doesn't need to be updated when the services change. Only downside is that opening a connection is slightly slower, and auto-complete in IDEs don't play well with it. Maybe a similar approach would work for your client as JS would allow this kind of dynamic class creation?

The C++, Java and C# clients generate services stubs in a similar manner to how your client currently works. As these are compiled languages and don't really allow dynamically generating code this is the only way to go. The services are generated from a JSON file containing all the information that would be returned by a call to GetServices. This means that the service code can be generated without needing KSP+kRPC running. This JSON file is distributed in the kRPC release archive, for example under `GameData/kRPC/KRPC.SpaceCenter.json`. You might want to change to use that rather than needing a server running to generate the code.

**Comment by eXigentCoder** [comment]
Thanks, that makes a lot of sense with the version management. I assume the krpc.proto file doesn't change that often and when it does, that's one of the few times you would need to do a new release of the client?

After giving it some thought, I think we can get the best of both worlds: On connection to the server, the client can call `GetServices` and run it through the generation step, overwriting the existing service definitions in the folder. The generation script is quick so the added overhead will be minimal. This would allow for the auto-completion in the IDE's and updated services without having to update the client all the time. Since the script is also just node code it won't require much tweaking to move it into the client initialisation either.
