### ISSUE TITLE
Fork krpc.js

### ISSUE THREAD

**Issue by lucaelin** [eXigentCoder/krpc-node#4]
Hello :)
A couple of weeks ago i discovered this very nice project and since I had a couple of days off, I got bored and forked it.. but changes to my new version (and my inability to properly use branches) are so drastic that I decided to publish it to a new repo. I hope you don't mind! If so, please let me know :)
My version is located under github.com/lucaelin/krpc.js
What do you think of the proposed changes and is there any way to collaborate on future versions of a javascript client for krpc?

**Comment by eXigentCoder** [comment]
Hey, I don't mind at all, glad more people are playing around with the code!
I'm a bit swamped at work at the moment, but I took a brief look over your repository, if I understand correctly you are putting together an example of how to use the library from a browser rather than a node process? Is that correct?
If so, I think that's a great idea, the barrier to entry is a lot lower when starting in the browser. I'm trying to keep all the examples together [in this repository](https://github.com/eXigentCoder/krpc-node-examples) I should probably make that link a bit bigger. I'd like to keep the core library as light weight as possible so that when people `npm install` it they get only the files they need.
We could use webpack to bundle your example there.

**Comment by lucaelin** [comment]
Glad to hear that you don't mind :+1: 
Yes my code does run in browsers, but that was actually just a byproduct :)
My main goal was to challenge myself to use ES2017 async/await syntax and remove the callback based approach. 
```javascript
let sc = krpc.services.spaceCenter;
let vessels = await sc.vessels;
sc.activeVessel = vessels[0];
let vessel = await sc.activeVessel;
let control = await vessel.control;
control.throttle = 0;
```
As you can see, I also moved getter and setter into a corresponding class structure.
Streams do automatically populate class properties, so you don't have to treat them any other way than regular property accesses.
But everything comes at a cost: 
No more can I generate documentation based on the service description since services are now generated at runtime...
It requires a fairly recent version of node (v7.10 I guess) and browsers (http://caniuse.com/#search=await)...
And my code really is a mess... as I said I only had a couple of days and no tests have been adapted(, yet).

**Comment by eXigentCoder** [comment]
Hey, so sorry for the radio silence, I've finally managed to free up some time and done some updates on the library thanks to your input:

- I have added support for async/await while still keeping the automatic document generation. 
- A bunch of improvements to the documentation itself 
- Removed references to the `util` and `os` libraries that are node specific to help make it more browser friendly
- Added prettier to auto-format the code.
- Updated the third party dependencies to the latest versions
- Exported a reference to each of the generated services on the base function for convenience and destructuring purposes.

I'm planning on adding browserify like you have done in your version so that people who chose to do so can run it from there.

There is also an issue that has been opened, #13 , which would bring your fork and this library closer together. 
Can you think of any other features you have added to your version that should be ported back here?

**Comment by lucaelin** [comment]
Happy to see all this progress! :+1: 
My fork currently tries to evaluate different methods of handling streams in a subtle, yet powerful manner. I'm not quite happy with the results at this point, but I'd be happy to share my findings as soon as i am!
Another thing my fork did was to get rid of the EventEmitter... I'm not sure whether or not this should be kept in the code, but I've never used it, since my "high level" service abstraction never required such a low level functionality and it kept throwing unhandled exceptions at me :laughing: .
All the other things I've changed are related to the dynamic hierarchal structure i guess...
